# Generated by Django 4.2 on 2024-08-06 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('place', models.CharField(max_length=40)),
                ('picture', models.ImageField(upload_to='artist_images')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('year_release', models.DateField()),
                ('gender', models.CharField(choices=[('HIP-HOP', 'Hip-Hop'), ('REGGAE', 'Reggae'), ('POP', 'Pop'), ('ROCK', 'Rock'), ('JAZZ', 'Jazz'), ('CLASSICAL', 'Classical'), ('BLUES', 'Blues')], max_length=30)),
                ('picture', models.ImageField(upload_to='album_images')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_manager.artist')),
            ],
        ),
    ]
